Base line model using linear regression, linearRegression model from sklearn and use fit() method.


In [51]:
import numpy as np
import pandas as pd
import os 

In [54]:
x_train = pd.read_csv(r"C:\Users\longv\Prediction-House-Price\Data\handle data\X_train.csv")
y_train = pd.read_csv(r"C:\Users\longv\Prediction-House-Price\Data\handle data\y_train.csv")
x_test = pd.read_csv(r"C:\Users\longv\Prediction-House-Price\Data\handle data\X_test.csv")
y_test = pd.read_csv(r"C:\Users\longv\Prediction-House-Price\Data\handle data\y_test.csv")

In [55]:
x_train = x_train.drop(columns = ['Id'])
x_test = x_test.drop(columns = ['Id'])
y_train =  np.log1p(y_train)/2
y_test =  np.log1p(y_test)/2

In [56]:
y_train

SalePrice
0      5.942248
1      6.044772
2      5.675209
3      6.036273
4      5.875975
...         ...
1163   6.040348
1164   5.906519
1165   5.826348
1166   6.077261
1167   6.033408

[1168 rows x 1 columns]

In [57]:
X_train = x_train.to_numpy()
y_train = y_train.to_numpy()


In [45]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [46]:
lr_model = LinearRegression().fit(X_train, y_train)

In [48]:
predict_train = lr_model.predict(X_train)
predict_train

array([[11.09669152],
       [11.44646982],
       [10.71065579],
       ...,
       [11.13060129],
       [11.26624188],
       [11.5588564 ]])

In [38]:
train_error_MAE = mean_absolute_error(np.exp(predict_train), np.exp(y_train))/len(predict_train)
train_error_MAE

15.39302218604834

In [39]:
X_test =  pd.read_csv(r"C:\Users\longv\Prediction-House-Price\Data\handle data\X_test.csv")
y_test = pd.read_csv(r"C:\Users\longv\Prediction-House-Price\Data\handle data\y_test.csv")
                     

In [14]:
X_test = X_test.drop(columns = ['Id'])
X_test = X_test.to_numpy()
y_test = y_test.to_numpy()

In [19]:
y_test

array([[154500],
       [325000],
       [115000],
       [159000],
       [315500],
       [ 75500],
       [311500],
       [146000],
       [ 84500],
       [135500],
       [145000],
       [130000],
       [ 81000],
       [214000],
       [181000],
       [134500],
       [183500],
       [135000],
       [118400],
       [226000],
       [155000],
       [210000],
       [173500],
       [129000],
       [192000],
       [153900],
       [181134],
       [141000],
       [181000],
       [208900],
       [127000],
       [284000],
       [200500],
       [135750],
       [255000],
       [140000],
       [138000],
       [219500],
       [310000],
       [ 97000],
       [114500],
       [205000],
       [119500],
       [253293],
       [128500],
       [117500],
       [115000],
       [127000],
       [451950],
       [144000],
       [119000],
       [196000],
       [115000],
       [287000],
       [144500],
       [260000],
       [213000],
       [175000],
       [107000

In [21]:
predict_test = lr_model.predict(X_test)
np.exp(predict_test)

array([[155275.44548283],
       [305319.01797485],
       [114397.69967007],
       [170758.49701843],
       [302364.2215133 ],
       [ 82189.20862702],
       [234006.33562795],
       [148372.56596138],
       [ 82343.4525754 ],
       [142302.10799336],
       [146520.78099965],
       [121730.18187167],
       [ 91433.17843958],
       [194214.17095109],
       [188891.49828685],
       [134963.76086604],
       [205560.436054  ],
       [129457.28106317],
       [111721.27977384],
       [216427.60100747],
       [166770.85507008],
       [204214.52397199],
       [183901.49184982],
       [133682.42656074],
       [201056.57607972],
       [144918.34207002],
       [190699.36854462],
       [ 96144.91412353],
       [177297.88220039],
       [179224.80975059],
       [120952.31924709],
       [265750.55485291],
       [189347.86037535],
       [104409.59874426],
       [273280.07512907],
       [154573.54220517],
       [136364.95561106],
       [215760.16552009],
       [3580

In [23]:
test_error_MAE =  mean_absolute_error(np.exp(predict_test), y_test)/len(predict_test)
test_error_MAE

65.61916332967272

Push lên competition 

In [24]:
test_comp = pd.read_csv(r"C:\Users\longv\Prediction-House-Price\Data\raw data\test.csv")

In [25]:
test_comp = test_comp.fillna(0)
test_comp = test_comp.to_numpy()

In [32]:
predict_comp = lr_model.predict(test_comp)
predict_comp=np.exp(predict_comp)

In [33]:
df_test = pd.read_csv(r"C:\Users\longv\Downloads\house-prices-advanced-regression-techniques\test.csv")

In [34]:
df_test['Prediction'] = predict_comp

In [35]:
df_test[['Id','Prediction']].to_csv(r"C:\Users\longv\predict.csv", index = False)