Base line model using linear regression


In [50]:
import numpy as np
import pandas as pd
import os 

In [51]:
x_train = pd.read_csv(r"D:\Machine Learning\Final Project DEADLINE 17-5\Prediction-House-Price\Data\handle data\X_train.csv")
y_train = pd.read_csv(r"D:\Machine Learning\Final Project DEADLINE 17-5\Prediction-House-Price\Data\handle data\y_train.csv")

In [52]:
x_train = x_train.drop(columns = ['Id'])

### input normalization

In [53]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(x_train)
X_train

array([[2.000e+01, 7.000e+01, 8.400e+03, ..., 0.000e+00, 6.000e+00,
        2.010e+03],
       [6.000e+01, 5.900e+01, 7.837e+03, ..., 0.000e+00, 5.000e+00,
        2.009e+03],
       [3.000e+01, 6.700e+01, 8.777e+03, ..., 0.000e+00, 5.000e+00,
        2.008e+03],
       ...,
       [2.000e+01, 6.000e+01, 8.172e+03, ..., 0.000e+00, 4.000e+00,
        2.006e+03],
       [5.000e+01, 5.500e+01, 7.642e+03, ..., 0.000e+00, 6.000e+00,
        2.007e+03],
       [1.200e+02, 5.300e+01, 3.684e+03, ..., 0.000e+00, 6.000e+00,
        2.009e+03]])

In [54]:
y_train = y_train.to_numpy()
y_train

AttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'

In [55]:
X_train_scaled

array([[-0.8667643 ,  0.35953495, -0.21289571, ..., -0.09274033,
        -0.13341669,  1.65006527],
       [ 0.07410996,  0.04874271, -0.26524463, ..., -0.09274033,
        -0.5080097 ,  0.89367742],
       [-0.63154574,  0.27477343, -0.17784146, ..., -0.09274033,
        -0.5080097 ,  0.13728958],
       ...,
       [-0.8667643 ,  0.07699655, -0.23409563, ..., -0.09274033,
        -0.88260272, -1.37548612],
       [-0.16110861, -0.06427265, -0.28337613, ..., -0.09274033,
        -0.13341669, -0.61909827],
       [ 1.48542135, -0.12078033, -0.65139925, ..., -0.09274033,
        -0.13341669,  0.89367742]])

In [56]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [57]:
lr_model = LinearRegression().fit(X_train_scaled, y_train)

In [58]:
predict_train = lr_model.predict(X_train_scaled)


In [59]:
train_error_MAE = mean_absolute_error(predict_train, y_train)/len(predict_train)
train_error_MAE

17.878337762142028

In [60]:
X_test =  pd.read_csv(r"D:\Machine Learning\Final Project DEADLINE 17-5\Prediction-House-Price\Data\handle data\X_test.csv")
y_test = pd.read_csv(r"D:\Machine Learning\Final Project DEADLINE 17-5\Prediction-House-Price\Data\handle data\y_test.csv")
                     

In [61]:
X_test = X_test.drop(columns = ['Id'])
X_test_scaled = scaler.fit_transform(X_test)
X_test_scaled = X_test_scaled.to_numpy()
y_test = y_test.to_numpy()

AttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'

In [67]:
X_test_scaled

array([[-0.89667773,  0.34892664, -0.24021623, ..., -0.15626413,
        -1.48022618, -1.33725768],
       [ 0.07037637,  1.2384883 ,  0.4136015 , ..., -0.15626413,
        -0.77281858,  1.62653163],
       [-0.65491421, -0.09585419, -0.14729991, ..., -0.15626413,
        -1.12652238,  1.62653163],
       ...,
       [ 0.07037637,  0.12653623, -0.27680415, ..., -0.15626413,
         1.34940422,  0.14463698],
       [ 0.31213989,  0.03122605, -0.12619804, ..., -0.15626413,
         1.34940422,  0.88558431],
       [-0.89667773,  0.34892664, -0.29024809, ..., -0.15626413,
         0.28829282,  0.88558431]])

In [63]:
predict_test = lr_model.predict(X_test_scaled)

In [70]:
train_error_MSE = mean_squared_error(predict_test, y_test)/len(predict_test)
train_error_MSE

1.722534687060383e+27

In [69]:
test_error_MAE =  mean_absolute_error(predict_test, y_test)/len(predict_test)
test_error_MAE

2057573436755.9062

Push lên competition 

In [51]:
test_comp = pd.read_csv(r"C:\Users\longv\Prediction-House-Price\Data\raw data\test.csv")

In [57]:
test_comp = test_comp.fillna(0)
test_comp = test_comp.to_numpy()

In [59]:
predict_comp = lr_model.predict(test_comp)

In [61]:
df_test = pd.read_csv(r"C:\Users\longv\Downloads\house-prices-advanced-regression-techniques\test.csv")

In [63]:
df_test['Prediction'] = predict_comp

In [66]:
df_test[['Id','Prediction']].to_csv(r"C:\Users\longv\predict.csv", index = False)